server:
  port: 8080
spring:
  application:
    #应用名称 , 可选
    name: college_take_out
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://192.168.21.129:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 123456abc

#读写分离配置，shardingjdbc
  shardingsphere:
    datasource:
      names: master,slave

      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.21.129:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456abc
      # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.21.146:3306/reggie?characterEncoding=utf-8&useSSL=false
        username: root
        password: root

    masterslave:
      #读写分离配置
      load-balance-algorithm-type: round_robin #轮训
      #最终数据源的名称
      name: dataSource
      #祖库数据源
      #从库数据源名字列表,多个逗号分离
      slave-data-source-names: slave
      master-data-source-name: master
    props:
      sql:
        show: true #开启SQL显示，默认false

  main:
    #是如果当前项目中存在同名的bean,后定义的bean会覆盖先定义的。
    allow-bean-definition-overriding: true

  redis:
    host: 192.168.21.129
    port: 6379
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存过期时间
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射 address_book ---> AddressBook
    map-underscore-to-camel-case: true
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


reggie:
  path: D:\img\